---
deployment:
  tasks:
    - export DEPLOYPATH=/home/irlmoppm/Main/
      
    # Production deployment
    - if [ "$BRANCH" == "Main" ]; then
        /bin/cp -R build/* $DEPLOYPATH;
      fi

    # Clear cache for both environments
    - if [ -f $DEPLOYPATH/cache/* ]; then
        /bin/rm -rf $DEPLOYPATH/cache/*;
      fi